### PR TITLE
Unit test configured

### LINKED ISSUE #2: Tests
This project does not have tests written for it.

### PR DESCRIPTION
**Pull request by Xavier577**
I have configured the test so we can import modules via the esm without any errors using babel and I have written test for generateVideoTag util function.  

image

don't mind the redlines, that's eslint acting up on my editor but the test runs.

### CODE REVIEW

**Comment by bolubee101** [comment]
This is awesome man. Thank you. Just a couple of things.
Can you please move the tests to the test folder?
Also, in the jest config file, please remove all the commented-out scaffold code.

**Comment by Xavier577** [comment]
yh sure I'll do that real quick

**Comment by bolubee101** [comment]
Perfect. With the power bestowed on me, by myself, I hereby approve this PR in my name. 

thumbs up

**Comment by Xavier577** [comment]
🤩🤩🤩🤩

**Comment by deejinng** [comment]
Hoping to get to this kind of level some days 😊

**Pull request merged**
